# Site settings
title: zjyao's blog
header-img: img/home-bg.jpg
email: string_yao@163.com
description: "一个金融民工的自我修养"
baseurl: ""
url: "https://stringyao.github.io"
facebook_username: zjyao
github_username: zjyao
linkedin_username: zjyao

# Build settings
markdown: kramdown
highlighter: rouge
future: true
permalink: /:title/
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

analytics :
  provider : google
  google : 
    tracking_id : 'UA-89904117-1'
  getclicky :
    site_id : 
